language: php

php:
- '5.6'
- '7.0'
- hhvm

before_script:
- composer install

after_success:
- travis_retry php vendor/bin/coveralls -v

notifications:
  email:
    on_failure: always
    recipients:
      - ptdorf@gmail.com
